
name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 13 * * *' # Every day at 1pm.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: mkdir pc
        run: mkdir build_pc
      - name: cmake build pc
        run: cmake -Bbuild_pc -H.
      - name: cmake make pc
        run: cmake --build build_pc/ --target all
      - name: run unit tests
        run: cd build_pc && ctest
      - name: install arm gcc
        run: sudo apt-get install gcc-arm-none-eabi
      - name: mkdir arm
        run: mkdir build_arm
      - name: cmake build arm
        run: cmake -DCMAKE_TOOLCHAIN_FILE=embedded/toolchain.cmake -DCMAKE_BUILD_TYPE=MinSizeRel -Bbuild_arm -H.
      - name: cmake make arm
        run: cmake --build build_arm/ --target all
      - name: print firmware stats
        run: arm-none-eabi-size build_arm/projects/*.elf
