
name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ARM toolchain
        run: sudo apt-get install gcc-arm-none-eabi
      - name: mkdir pc
        run: mkdir build_pc
      - name: cmake build pc
        run: cmake -Bbuild_pc -H.
      - name: cmake make pc
        run: cmake --build build_pc/ --target all
      - name: run unit tests
        run: cd build_pc && ctest
      - name: mkdir arm
        run: mkdir build_arm
      - name: cmake build arm
        run: cmake -DCMAKE_TOOLCHAIN_FILE=embedded/toolchain.cmake -Bbuild_arm -H.
      - name: cmake make arm
        run: cmake --build build_arm/ --target all
